server:
    port: 8080
path:
    ffmpeg:
        centos: /usr/bin/ffmpeg
        linux: /usr/bin/ffmpeg
        macosx: /usr/local/Cellar/ffmpeg/3.4/bin/ffmpeg
    folder:
        original: /tmp/VideoTranscoding/videos/original/
        ouput: /tmp/VideoTranscoding/videos/transcoded/
spring:
    datasource:
        # driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:postgresql://192.168.3.145:5432/postgres?autoReconnect=true
        username: root
        password: 1234
    jpa:
        database: postgresql
        open-in-view: true
        properties:
          hibernate:
            globally_quoted_identifiers: true
            show_sql: false
            use_sql_comments: true
            format_sql: true
            ddl-auto: none
            dialect: org.hibernate.dialect.PostgreSQL95Dialect        
            
