name: Build and push to dockerhub
on: 
  push: 
    paths-ignore:
    - 'api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: |
          npm install 
      - name: Npm build prod 
        run: |   
          npm run build --prod
      - name: Dockerhub login
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.6.1
        with:
          version: latest
      - name: Available platforms on docker buildx
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker Buildx and (push)
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag "luiscajl/videotranscoding-frontend:latest" \
            --file Dockerfile .
      - name: Docker Check Manifest
        if: always() && startsWith(github.ref, 'refs/tags/')
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
      - name: Clear
        if: always() && startsWith(github.ref, 'refs/tags/')
        run: |
          rm -f ${HOME}/.docker/config.json
